# Generated by Django 5.0.3 on 2024-09-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordreset",
            old_name="created_when",
            new_name="created_time",
        ),
    ]
