# Generated by Django 5.1.1 on 2024-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_restaurant_favoriterestaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="place_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="vicinity",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="restaurants/"),
        ),
    ]
