# Generated by Django 5.1.1 on 2024-09-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewrating",
            old_name="restaurnat",
            new_name="restaurant",
        ),
    ]
