# Generated by Django 5.1.1 on 2024-09-28 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_restaurnat_reviewrating_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=255, upload_to="store/products"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "restaurantgallery",
                "verbose_name_plural": "restaurant gallery",
            },
        ),
    ]
