# Generated by Django 5.1.1 on 2024-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_restaurantgallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantgallery",
            name="image",
        ),
        migrations.AddField(
            model_name="restaurantgallery",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
